### ISSUE TITLE
Allow multiple signatures to be defined in your configuration file

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-aspnetcore#1]
### Motivation

Webhooks in Kentico Kontent can only define one secret webhook key per URL. As such we have had to make multiple end point definitions in dev / test. In addition due to the issue of no distributed caching ability we have had to make multiple webhook endpoints to identify each node of a load balanced cluster.

This necessitates multiple webhook secrets to be defined in a configuration file.

Here is an example:

![image](https://user-images.githubusercontent.com/6610039/80217156-d339e780-8604-11ea-93c3-9c76002c80d1.png)

### Proposed solution

We solved this by allowing multiple webhook secrets to be defined as follows:

```
       public async Task InvokeAsync(HttpContext httpContext, IOptions<ProjectOptionsBase> projectOptions)
        {
            var request = httpContext.Request;
            request.EnableBuffering();

            using var reader = new StreamReader(request.Body, Encoding.UTF8, true, 1024, true);
            var content = await reader.ReadToEndAsync();
            request.Body.Seek(0, SeekOrigin.Begin);

            // Iterates through all secrets to allow us to use multiple Kentico projects content.
            var generatedSignatures = new List<string>();
            foreach (var sig in projectOptions.Value.KenticoKontentWebhookSecrets)
                generatedSignatures.Add(GenerateHash(content, sig));

            var signature = request.Headers["X-KC-Signature"].FirstOrDefault();

            if (!generatedSignatures.Contains(signature))
            {
                httpContext.Response.StatusCode = 401;
                return;
            }

            await _next(httpContext);
        }
```

Easy fix would be to do the same thing, and make your WebhookOptions model be an array of strings so you could define them in a config file as follows:

```
  "KenticoKontentWebhookSecrets": [
    ".....", // Matt's ARRT.ORG Ngrok Dev Endpoint
    ".....", // Chris ARRT.ORG NGrok Dev Endpoint
    ".....", //cdevwww2hook.arrt.org
    "....." //tdevwww2hook.arrt.org
  ],
```

**Comment by petrsvihlik** [comment]
Wouldn't this better be solved by using multiple per-env configs?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1

![image](https://user-images.githubusercontent.com/9810625/80221505-ab1ea880-8645-11ea-8f46-dae4aec615ce.png)

**Comment by xantari** [comment]
Yeah, that is the other way of doing it. It's just that we would have a lot of extra configurations and each load balanced node would need their own configuration. This would also mean a configuration for each developer for their own local webhook...

**Comment by xantari** [comment]
Currently this is the only setting that would necessitate all these extra environment configurations in our current project,.. I'd be more inclined to keep the signature handler we have instead of using the new one to avoid all these extra environment configs.

**Comment by petrsvihlik** [comment]
Thanks for the explanation!

I understand your arguments but it is the best practice to do it that way. That's exactly what the env-configs are meant for. If it's easier for you to do it differently then go ahead but I don't think it's a good idea to include the aforementioned functionality in this package. Therefore, I'd close the issue now.

If you disagree, feel free to reopen this issue and add more comments.

**Comment by xantari** [comment]
Sounds good, thanks for taking a look.
