### ISSUE TITLE
Make webhook signature validator work with new webhooks

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-aspnetcore#15]
### Motivation

https://kontent.ai/learn/docs/webhooks/webhooks/net details a new webhook experience.

However, this library appears to still use X-KC-Signature HTTP header for the webhook signature validator.

It appears the new HTTP Header is "X-Kontent-ai-Signature".

### Proposed solution

Create a new signature validator and differentiate the current one as "legacy" perhaps?

**Comment by pokornyd** [comment]
hello and thanks for the submission. I'll review the validation method and update them to be in line with the reworked webhook experience. until then, you may use the validation approach outlined in our documentation: https://kontent.ai/learn/docs/webhooks/webhooks/net#a-validate-received-notifications

**Comment by pokornyd** [comment]
PR linked. Since the validation logic remains the same and only the header name is changed, I opted for modification of the existing implementation, rather than duplicating the code.
